CREATE TABLE IF NOT EXISTS marry_on_comment (
  id INT(6) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  target VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
